In [1]:
import numpy as np

In [3]:
# tao mang
a = np.array([1,2,3])
# in mang
print(a)

[1 2 3]


In [4]:
# in ra 1 phan tu
element = a[1]
print(element)

2


In [7]:
# tao mang 2 chieu
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix")
print(matrix)

# in 1 phan tu
element = matrix[1,2]
print(element)

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [9]:
# cach tao mang
# cach tao mang toan so 0
a = np.zeros(5)
print(a)

# cach tao mang toan so 1
a = np.ones(5)
print(a)

# tao mang
a = np.empty
print(a)

#tao mang tu 0 den 99
a = np.arange(100)
print(a)

# tao mang gom cac phan tu voi khoang cach deu nhau
a = np.linspace(0, 10, num=5)
print(a)

# xac dinh kieu du lieu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
<built-in function empty>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [10]:
# them , xoa , sap xep mang
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [11]:
# sap xep
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [13]:
# sap xep nguoc
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [14]:
# them phan tu vo mang
arr = np.append(arr, 100)
print(arr)

[  5   4   3   2   1 100]


In [15]:
# xoa di 1 vi tri nao do trong mang
arr = np.delete(arr, 3)
print(arr)

[  5   4   3   1 100]


In [16]:
# tao 1 mang 2 chieu
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tang dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # giam dan
print(sap_xep_theo_cot)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [17]:
# tao 1 mang 2 chieu
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giam dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # tang dan
print(sap_xep_theo_cot)

[[3 2 1]
 [8 6 4]
 [9 7 5]]
[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [18]:
# tao 1 mang 2 dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])
#su dung cac thuoc tinh de lay thong tin ve mang
so_chieu = arr.ndim # so chieu (2 chieu)
kich_thuoc = arr.size # kich thuoc ( tong so phan tu (6) )
hinh_dang = arr.shape # hinh dang (so hang vs so cot ((2, 3 ))

print("so chieu:", so_chieu)
print("kich thuoc:", kich_thuoc)
print("hinh dang:", hinh_dang)

so chieu: 2
kich thuoc: 6
hinh dang: (2, 3)


In [19]:
# chuyen doi kieu du lieu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [20]:
# thay doi hinh dang cua mang
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
# chuyen mang thanh 1 chieu
reshaped_arr = reshaped_arr.flatten()
print(reshaped_arr)

[1 2 3 4 5 6]


In [22]:
# cat lat mang
arr = np.array([1, 2, 3, 4, 5])
# cat tu phan tu 1 -> 4
sub_arr = arr[1:4]
print(sub_arr)

[2 3 4]


In [23]:
sub_arr = arr[:-1]
print(sub_arr)

[1 2 3 4]


In [24]:
sub_arr = arr[-2:]
print(sub_arr)

[4 5]


In [25]:
# chuyen vi mang
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
# noi mang
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [28]:
# ham tinh tong ( sum )
# ham numpy.sum() cho phep tinh tong cac phan tu trong mang
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("tong cua mang arr:", total)

tong cua mang arr: 15


In [29]:
# ham numpy.mean() tinh gia tri trung binh cua cac phan tu trong mang 

In [31]:
average = np.mean(arr)
print("gia tri trung binh cua mang arr:", average)

gia tri trung binh cua mang arr: 3.0


In [32]:
# ham numpy.max() va numpy.min() dung de tim gia tri max va min trong mang
max_value = np.max(arr)
min_value = np.min(arr)
print("gia tri max trong mang arr:", max_value)
print("gia tri min trong mang arr:", min_value)

gia tri max trong mang arr: 5
gia tri min trong mang arr: 1


In [39]:
# ham numpy.sdt() tinh do lech chuan cua mang , do luong muc do phan tan cua du lieu
std_deviation = np.std(arr)
print("do lech chuan cua mang arr:", std_deviation)

do lech chuan cua mang arr: 1.4142135623730951


In [40]:
# ham numpy.var() tinh phuong sai cua mang , do luong muc do bien thien cua du lieu
variance = np.var(arr)
print("phuong sai cua mang arr:", std_deviation)

phuong sai cua mang arr: 1.4142135623730951


In [41]:
# ham numpy.dot() tinh tong tich chap cua 2 mang (vector)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("tong tich chap cua arr1 và arr2:", dot_product)

tong tich chap cua arr1 và arr2: 32
